// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClearDiskLogs():Promise<Record<string, any>>;

export function ClearLogs():Promise<void>;

export function CreateSong(arg1:string,arg2:string,arg3:main.SongOptions):Promise<string>;

export function DeleteAllAICovers():Promise<Record<string, any>>;

export function DeleteAllDemucs():Promise<Record<string, any>>;

export function DeleteAllOriginals():Promise<Record<string, any>>;

export function DeleteAllSeparated():Promise<Record<string, any>>;

export function DeleteLocalFile(arg1:string,arg2:string):Promise<boolean>;

export function DeleteModel(arg1:string):Promise<boolean>;

export function DownloadFile(arg1:string,arg2:string):Promise<Record<string, string>>;

export function ExportLogs():Promise<string>;

export function GetAICoverFiles():Promise<Array<string>>;

export function GetAudioCleanupSettings():Promise<Record<string, boolean>>;

export function GetAudioUrl(arg1:string,arg2:string):Promise<string>;

export function GetAudioUrlByFullPath(arg1:string):Promise<string>;

export function GetDefaultOptions():Promise<main.SongOptions>;

export function GetDemucsFiles():Promise<Array<Record<string, string>>>;

export function GetDemucsProgress(arg1:string):Promise<main.DemucsProgress>;

export function GetDeviceSetting():Promise<string>;

export function GetFileStreamUrl(arg1:string,arg2:string):Promise<string>;

export function GetJobProgress(arg1:string):Promise<Record<string, any>>;

export function GetLogStats():Promise<Record<string, number>>;

export function GetLogs(arg1:string,arg2:string,arg3:string):Promise<Array<main.LogEntry>>;

export function GetOriginalFiles():Promise<Array<string>>;

export function GetSeparatedFiles():Promise<Array<string>>;

export function GetStoredModels():Promise<Array<string>>;

export function MergeAudio(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<Record<string, string>>;

export function MergeMultiTrack(arg1:main.MultiTrackMixRequest):Promise<Record<string, string>>;

export function SaveAudioCleanupSettings(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean):Promise<boolean>;

export function SaveDeviceSetting(arg1:string):Promise<boolean>;

export function SaveFileAs(arg1:string,arg2:string):Promise<Record<string, string>>;

export function SelectAndSaveAudio():Promise<Record<string, string>>;

export function SelectAndSaveModel():Promise<Record<string, string>>;

export function StartDemucsJob(arg1:main.DemucsRequest):Promise<main.DemucsResponse>;
