// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSong(arg1:string,arg2:string,arg3:number):Promise<string>;

export function DeleteModel(arg1:string):Promise<boolean>;

export function GetJobProgress(arg1:string):Promise<Record<string, any>>;

export function GetStoredModels():Promise<Array<string>>;

export function SelectAndSaveAudio():Promise<Record<string, string>>;

export function SelectAndSaveModel():Promise<Record<string, string>>;
