// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateSong(arg1:string,arg2:string,arg3:main.SongOptions):Promise<string>;

export function DeleteLocalFile(arg1:string,arg2:string):Promise<boolean>;

export function DeleteModel(arg1:string):Promise<boolean>;

export function DownloadFile(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetAICoverFiles():Promise<Array<string>>;

export function GetAudioUrl(arg1:string,arg2:string):Promise<string>;

export function GetAudioUrlByFullPath(arg1:string):Promise<string>;

export function GetDefaultOptions():Promise<main.SongOptions>;

export function GetDeviceSetting():Promise<string>;

export function GetFileStreamUrl(arg1:string,arg2:string):Promise<string>;

export function GetJobProgress(arg1:string):Promise<Record<string, any>>;

export function GetOriginalFiles():Promise<Array<string>>;

export function GetSeparatedFiles():Promise<Array<string>>;

export function GetStoredModels():Promise<Array<string>>;

export function MergeAudio(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Record<string, string>>;

export function SaveDeviceSetting(arg1:string):Promise<boolean>;

export function SaveFileAs(arg1:string,arg2:string):Promise<Record<string, string>>;

export function SelectAndSaveAudio():Promise<Record<string, string>>;

export function SelectAndSaveModel():Promise<Record<string, string>>;
