// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLog'](arg1, arg2, arg3);
}

export function ClearDiskLogs() {
  return window['go']['main']['App']['ClearDiskLogs']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateSong(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSong'](arg1, arg2, arg3);
}

export function DeleteAllAICovers() {
  return window['go']['main']['App']['DeleteAllAICovers']();
}

export function DeleteAllDemucs() {
  return window['go']['main']['App']['DeleteAllDemucs']();
}

export function DeleteAllOriginals() {
  return window['go']['main']['App']['DeleteAllOriginals']();
}

export function DeleteAllSeparated() {
  return window['go']['main']['App']['DeleteAllSeparated']();
}

export function DeleteLocalFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocalFile'](arg1, arg2);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function GetAICoverFiles() {
  return window['go']['main']['App']['GetAICoverFiles']();
}

export function GetAudioCleanupSettings() {
  return window['go']['main']['App']['GetAudioCleanupSettings']();
}

export function GetAudioUrl(arg1, arg2) {
  return window['go']['main']['App']['GetAudioUrl'](arg1, arg2);
}

export function GetAudioUrlByFullPath(arg1) {
  return window['go']['main']['App']['GetAudioUrlByFullPath'](arg1);
}

export function GetDefaultOptions() {
  return window['go']['main']['App']['GetDefaultOptions']();
}

export function GetDemucsFiles() {
  return window['go']['main']['App']['GetDemucsFiles']();
}

export function GetDemucsProgress(arg1) {
  return window['go']['main']['App']['GetDemucsProgress'](arg1);
}

export function GetDeviceSetting() {
  return window['go']['main']['App']['GetDeviceSetting']();
}

export function GetFileStreamUrl(arg1, arg2) {
  return window['go']['main']['App']['GetFileStreamUrl'](arg1, arg2);
}

export function GetJobProgress(arg1) {
  return window['go']['main']['App']['GetJobProgress'](arg1);
}

export function GetLogStats() {
  return window['go']['main']['App']['GetLogStats']();
}

export function GetLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3);
}

export function GetOriginalFiles() {
  return window['go']['main']['App']['GetOriginalFiles']();
}

export function GetSeparatedFiles() {
  return window['go']['main']['App']['GetSeparatedFiles']();
}

export function GetStoredModels() {
  return window['go']['main']['App']['GetStoredModels']();
}

export function MergeAudio(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MergeAudio'](arg1, arg2, arg3, arg4, arg5);
}

export function MergeMultiTrack(arg1) {
  return window['go']['main']['App']['MergeMultiTrack'](arg1);
}

export function SaveAudioCleanupSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAudioCleanupSettings'](arg1, arg2, arg3, arg4);
}

export function SaveDeviceSetting(arg1) {
  return window['go']['main']['App']['SaveDeviceSetting'](arg1);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SelectAndSaveAudio() {
  return window['go']['main']['App']['SelectAndSaveAudio']();
}

export function SelectAndSaveModel() {
  return window['go']['main']['App']['SelectAndSaveModel']();
}

export function StartDemucsJob(arg1) {
  return window['go']['main']['App']['StartDemucsJob'](arg1);
}
