// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSong(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSong'](arg1, arg2, arg3);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function GetJobProgress(arg1) {
  return window['go']['main']['App']['GetJobProgress'](arg1);
}

export function GetStoredModels() {
  return window['go']['main']['App']['GetStoredModels']();
}

export function SelectAndSaveAudio() {
  return window['go']['main']['App']['SelectAndSaveAudio']();
}

export function SelectAndSaveModel() {
  return window['go']['main']['App']['SelectAndSaveModel']();
}
